# Site Info
title:              "Asapanna Rakesh"
description:        "Personal web protfolio"
author_name:        "Asapanna Rakesh" # change this to your name
logo_url:           https://i.ibb.co/DYgzHwg/dp.jpg # Get it from GitHub API: https://api.github.com/users/<username>
white_rabit:        https://raw.githubusercontent.com/rakesh4real/Brown-Corpus/master/flyingrabbit.gif # https://raw.githubusercontent.com/rakesh4real/Brown-Corpus/master/rabitwhite.jpg

# Site Settings
url:                https://rakesh4real.github.io # main url
baseurl:            /whoami
permalink:          /:title # Post permalink
timezone:           Asia/Kuala_Lumpur # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
mathjax:            true  # enables support for mathjax - set to 'false' to disable

# Site Build
highlighter:        rouge
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile", "script" ]
plugins:
  - jekyll-sitemap
  - jekyll-remote-theme

remote_theme: rakesh4real/whoami

defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"
